In [1]:
import pandas as pd
import numpy as np

The history saving thread hit an unexpected error (DatabaseError('database disk image is malformed')).History will not be written to the database.

In [4]:
peak_df = pd.read_csv("/cellar/users/aklie/data/datasets/igvf_sc-islet_10X-Multiome/annotation/timecourse/A2_control/snapatac2/filtered/filtered_peaks/SC.beta.filt.narrowPeak", sep="\t", header=None, names=["chrom", "start", "end", "X", "XX", "XXX", "name", "score", "strand", "signalValue", "pValue", "qValue", "peak"])

In [6]:
# Redo name column with "peak{i}"
peak_df["name"] = ["peak" + str(i) for i in range(1, peak_df.shape[0] + 1)]
peak_df

,chrom,start,end,X,XX,XXX,name,score,strand,signalValue,pValue,qValue,peak
0,chr1,9912,10561,.,.,.,peak1,1000,.,21.489363,196.430756,193.530823,201
1,chr1,231240655,231241684,.,.,.,peak2,1000,.,19.462137,492.384460,488.958649,552
2,chr1,212477106,212477534,.,.,.,peak3,1000,.,17.716049,249.786377,246.779495,218
3,chr1,214660925,214661583,.,.,.,peak4,1000,.,16.896984,229.103424,226.136063,194
4,chr1,214602831,214603561,.,.,.,peak5,1000,.,20.264317,503.696686,500.249786,313
...,...,...,...,...,...,...,...,...,...,...,...,...,...
70244,chrY,7344762,7345019,.,.,.,peak70245,124,.,4.748340,14.549810,12.465619,139
70245,chrY,2913216,2913452,.,.,.,peak70246,117,.,4.612673,13.807320,11.735338,109
70246,chrY,2838023,2838242,.,.,.,peak70247,105,.,3.885481,12.568950,10.519343,116
70247,chrY,5000714,5001282,.,.,.,peak70248,63,.,3.341289,8.257720,6.309133,252
70248,chrY,13704166,13704590,.,.,.,peak70249,50,.,2.652106,6.958510,5.052281,115

In [7]:
peak_df[["chrom", "start", "end", "name", "score", "strand", "signalValue", "pValue", "qValue"]].to_csv("/cellar/users/aklie/data/datasets/igvf_sc-islet_10X-Multiome/annotation/timecourse/A2_control/snapatac2/filtered/homer/known/SC.beta/SC.beta.filt.narrowPeak", sep="\t", header=False, index=False)